shallow_clone: true
configuration:
  - Release
before_build:
  - mkdir build
  - cd build
  - appveyor DownloadFile https://github.com/Wargus/stratagus/releases/download/2015-30-11/dependencies.zip
  - 7z x dependencies.zip
  - choco install nsis -pre
  - cmake -G "Visual Studio 14 2015" -DCMAKE_PREFIX_PATH="%cd%\\dependencies" -DENABLE_NSIS=ON ..
  - cd ..
artifacts:
  - path: build\Stratagus-*.exe
deploy:
  release: master-builds
  description: 'Automatic builds from the master branch'
  provider: GitHub
  auth_token:
    secure:  I+Yd37ipF67x5pbsPtl5DX5+bf9q0bt6NFhrtUUauhkHDqn+IfZwyECkUITT98rw
  artifact: /.*exe/
  draft: false
  prerelease: true
  on:
    branch: master